# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config
, lib
, pkgs
, modulesPath
, ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # -------------------------
  # Root
  # -------------------------

  fileSystems."/" = {
    device = "/dev/mapper/luks-e0e627de-841c-4515-bbf4-de86025e2aed";
    fsType = "ext4";
  };

  # -------------------------
  # FILESYSTEMS
  # -------------------------

  boot.initrd.luks.devices."luks-e0e627de-841c-4515-bbf4-de86025e2aed".device =
    "/dev/disk/by-uuid/e0e627de-841c-4515-bbf4-de86025e2aed";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/2550-EA04";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };
  # -------------------------
  # SWAP (encrypted mapper)
  # -------------------------

  boot.initrd.luks.devices."luks-dd67d449-3478-460e-acc7-4890531c37d7".device =
    "/dev/disk/by-uuid/dd67d449-3478-460e-acc7-4890531c37d7";

  swapDevices = [
    { device = "/dev/mapper/luks-dd67d449-3478-460e-acc7-4890531c37d7"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
