# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config
, lib
, modulesPath
, pkgs
, ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "thunderbolt"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [
      "subvol=root"
      "compress=zstd"
      "noatime"
      "ssd"
    ];
  };

  fileSystems."/home/cuda/roms-one" = {
    device = "/dev/disk/by-uuid/73a2a196-b139-4ebd-b8bf-dec7769e3f46";
    fsType = "btrfs";
    options = [
      "compress=zstd"
      "noatime"
      "ssd"
    ];

  };

  fileSystems."/home/cuda/roms-two" = {
    device = "/dev/disk/by-uuid/6f28647c-7f32-4a6a-92d9-3edb6cbf880b";
    fsType = "btrfs";
    options = [
      "compress=zstd"
      "noatime"
      "ssd"
    ];
  };

  # Auto Decrypt for console experience
  boot.initrd.luks.devices."cryptroot" = {
    device = "/dev/disk/by-uuid/909dc85e-ee8c-4cc0-b5ae-e22fc12eae0c";
    keyFile = "/keyfile";
    allowDiscards = true;
    preLVM = true;
  };

  boot.initrd.secrets = {
    "/keyfile" = /root/.luks-keyfile;
  };

  fileSystems."/home" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [
      "subvol=home"
      "compress=zstd"
      "noatime"
      "ssd"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/cryptroot";
    fsType = "btrfs";
    options = [
      "subvol=nix"
      "compress=zstd"
      "noatime"
      "ssd"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/3C05-8626";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [{ device = "/swapfile"; }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  stylix.targets.plymouth.enable = false;
  # boot screen
  boot = {
    plymouth = {
      enable = true;
    };

    initrd.systemd.enable = true;
    # Enable "Silent boot"
    consoleLogLevel = 3;
    initrd.verbose = false;
    kernelParams = [
      "quiet"
      "splash"
      "rd.udev.log_level=3"
      "rd.systemd.show_status=auto"
    ];

    # Hide the OS choice for bootloaders.
    # It's still possible to open the bootloader list by pressing any key
    # It will just not appear on screen unless a key is pressed
    loader.timeout = 0;
  };

  # auto login
  services.displayManager.autoLogin.enable = true;
  services.displayManager.autoLogin.user = "cuda";
  services.displayManager.defaultSession = "plasma-bigscreen-wayland";
}
