# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, pkgs, ... }:
let
  variables = import ./variables.nix { pkgs = pkgs; };
  # inherit (variables) gitUsername;
in
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];
  boot.kernelParams =
    [ "intel_iommu=on" "iommu=pt" "vfio-pci.ids=${variables.vfioIds}" ];

  boot.initrd.availableKernelModules =
    [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/af05cf46-3c34-4c6c-bd24-b25f2287aa83";
    fsType = "ext4";
  };

  fileSystems."/mnt/SSD" = {
    device = "/dev/disk/by-uuid/05353c4a-1793-40d5-a185-f2ed019126a1 ";
    fsType = "btrfs";
    options = [ "nofail" ];
  };
  boot.initrd.luks.devices."luks-49b6cc8e-a559-4748-b78a-dad3b31f2325".device =
    "/dev/disk/by-uuid/49b6cc8e-a559-4748-b78a-dad3b31f2325";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/8C78-571B";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp15s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp14s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;

  #Merge SSD storage into home directory
  systemd.services.bind-ssd-folders = {
    description = "Bind mount all directories from /mnt/SSD into /home/shiba";

    # Ensure the SSD and normal file systems are up
    after = [ "local-fs.target" ];
    wants = [ "local-fs.target" ];
    wantedBy = [ "multi-user.target" ];

    serviceConfig.Type = "oneshot";

    path = [
      pkgs.util-linux # mount, umount, basename, etc.
      pkgs.coreutils # mkdir, test, etc.
    ];

    script = ''
      for d in /mnt/SSD/*; do
        if [ -d "$d" ]; then
          name="$(basename "$d")"
          target="/home/${variables.hostName}/$name"

          mkdir -p "$target"
          mount --bind "$d" "$target"
        fi
      done
    '';
  };
}
