# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib
, modulesPath
, ...
}:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = [
    "ahci"
    "xhci_pci"
    "virtio_pci"
    "sr_mod"
    "virtio_blk"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-86424f50-67aa-4947-865e-89c379b3e264";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-86424f50-67aa-4947-865e-89c379b3e264".device =
    "/dev/disk/by-uuid/86424f50-67aa-4947-865e-89c379b3e264";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/37C2-5E5D";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-90fcbf07-154d-47ae-8139-a98ae2e22947"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
